version: "3.9"
services:
  lra-coordinator:
    image: "quay.io/jbosstm/lra-coordinator:latest"
    network_mode: "host"
  amq-broker:
    image: "registry.redhat.io/amq7/amq-broker-rhel8:7.11.0"
    environment:
      - AMQ_USER=admin
      - AMQ_PASSWORD=admin
      - AMQ_REQUIRE_LOGIN=true
    ports:
      - "8161:8161"
      - "61616:61616"
